name: Test Application

on:
  push:
    branches:
      - workflow
  pull_request:
    branches:
      - workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # (Got deprecation warnings and unsure compatibility message for the lastest version of node.js I am using) Node.js version 20
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
